### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by ld892012** [ArtemIzmaylov/aimp_lancast#1]
Hello

The AddOn shows an error when i trying to start a server :
![image](https://github.com/ArtemIzmaylov/aimp_lancast/assets/17686344/aaa1ead6-b545-4267-bce2-165ce883457b)

Where i can find more information about this error ?

Thanks in advance

**Comment by ArtemIzmaylov** [comment]
Ensure that Windows Media codec is installed to your OS

**Comment by ld892012** [comment]
~~I have checked presence of Windows Media player and it was already installed so i launched Windows media player and now Lancast work perfectly.
Maybe Windows Media Player needs to be opened at least one time to make it work~~

OK I just realized it didn't work when i set AIMP's audio output to more channels than 2, it works when i set it to stereo ^^
